### ISSUE TITLE
Any particular reason nested classes aren't namespaced?

### ISSUE THREAD

**Issue by timbur** [jsstyles/jss-nested#6]
Just curious.  Perhaps I'm using `jss` wrong?

**Comment by timbur** [comment]
I should probably elaborate.  I'll do that with an example.

```js
export const styles = {
  "icon": {
    "color": "#f00"
  },
  "item": {
    "background": "#0f0",
    "& icon": {
      "color": "#00f"
    }
  }
}
```

I expected the `icon` under `item` to match the top-level `icon`.  Am I overlooking some key concept or something?

**Comment by kof** [comment]
if your dom element .item is one of the parents of .icon - yes. You need to use the plugin for nesting https://github.com/jsstyles/jss-nested

Also I would advise to use namespaced rules and let jss generate classes. Your code will only work if you set `named: false`

**Comment by kof** [comment]
Look into the DOM and see the generated style element.

**Comment by timbur** [comment]
Yeah, I concluded that I should avoid as many nested selectors as possible, but I am using `jss-nested` and it doesn't seem to be working?  Or maybe I'm misunderstanding how it works?

```js
import jss from 'jss';
import jssNested from 'jss-nested';

jss.use(jssNested);

export const styles = {
  ".icon": {
    "color": "#f00"
  },
  ".item": {
    "background": "#0f0",
    "& .icon": {
      "background": "#00f"
    }
  }
}
```

Ultimately generates:
```css
.jss-34 {
  color: #f00;
}
.jss-35 {
  background: #0f0;
}
.jss-35 .icon {
  background: #00f;
}
```

**Comment by timbur** [comment]
Tomorrow I will go through my code and try to remove as many nested selectors as possible (there aren't many to begin with), but I would like to understand how `jss-nested` is supposed to work (beyond pseudo-selectors).

**Comment by kof** [comment]
as I said, you don't specify `named: false` and yet try to use custom selectors.

**Comment by kof** [comment]
Avoid custom selectors, use namespaces.

**Comment by timbur** [comment]
I see.  Thanks!
